# Java Code Quality Manual Test Workflow
#
# Purpose:
# This workflow allows manual testing of the action against Java code files.
# It scans all files (not just changed ones) and is useful for:
# - Testing the action manually
# - Debugging issues
# - Demonstrating functionality
# - Running quality checks on any branch

name: Java Code Quality Manual Test

on:
  workflow_dispatch:
    inputs:
      # 🎯 WHAT TO SCAN (Core Configuration)
      config_preset:
        description: '🎯 What Java components do you want to scan?'
        required: false
        default: 'java-full'
        type: choice
        options:
          - 'java-full'
          - 'java-source'
          - 'java-tests'
          - 'custom'
      scan_path:
        description: '📁 Path to scan (where your Java test files are located)'
        required: true
        default: 'language-tests/java/files/'
        type: string
      file_types_config:
        description: '⚙️ Custom file types configuration (JSON) - only used if config_preset is "custom"'
        required: false
        default: ''
        type: string

      # ⚙️ HOW TO SCAN (Behavior Settings)
      enable_cache:
        description: '🚀 Enable caching for faster subsequent runs'
        required: false
        default: 'true'
        type: boolean
      output_formats:
        description: '📊 How do you want to see the results?'
        required: true
        default: 'github'
        type: choice
        options:
          - 'github'
          - 'github,json'
          - 'github,html'
          - 'github,text'
          - 'github,json,html'
          - 'github,json,text'
          - 'github,html,text'
          - 'github,json,html,text'
          - 'json'
          - 'html'
          - 'text'

      # 🚨 QUALITY THRESHOLDS (When to Fail)
      max_critical_violations:
        description: '🚨 Maximum critical violations allowed (security issues, major bugs)'
        required: true
        default: '50'
        type: string
      max_medium_violations:
        description: '⚠️ Maximum medium violations allowed (code quality issues)'
        required: true
        default: '100'
        type: string
      fail_on_issues:
        description: '❌ Should the workflow fail if violations exceed thresholds?'
        required: false
        default: 'false'
        type: boolean

jobs:
  code-quality-test:
    name: Manual Test on Java Files
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      # Set the configuration based on the preset choice
      - name: Set configuration
        id: set-config
        run: |
          case "${{ github.event.inputs.config_preset }}" in
            "java-full")
              CONFIG='[
                {
                  "name": "Java Source",
                  "sourcePath": "language-tests/java/files/src/main/java/",
                  "fileExtensions": [".java"],
                  "analyzer": "pmd",
                  "rulesPaths": [
                    "./language-tests/java/rulesets/pmd/standard-ruleset.xml"
                  ]
                },
                {
                  "name": "Java Tests",
                  "sourcePath": "language-tests/java/files/src/test/java/",
                  "fileExtensions": [".java"],
                  "analyzer": "pmd",
                  "rulesPaths": [
                    "./language-tests/java/rulesets/pmd/standard-ruleset.xml"
                  ]
                }
              ]'
              ;;
            "java-source")
              CONFIG='[
                {
                  "name": "Java Source",
                  "sourcePath": "language-tests/java/files/src/main/java/",
                  "fileExtensions": [".java"],
                  "analyzer": "pmd",
                  "rulesPaths": [
                    "./language-tests/java/rulesets/pmd/standard-ruleset.xml"
                  ]
                }
              ]'
              ;;
            "java-tests")
              CONFIG='[
                {
                  "name": "Java Tests",
                  "sourcePath": "language-tests/java/files/src/test/java/",
                  "fileExtensions": [".java"],
                  "analyzer": "pmd",
                  "rulesPaths": [
                    "./language-tests/java/rulesets/pmd/standard-ruleset.xml"
                  ]
                }
              ]'
              ;;
            "custom")
              CONFIG='${{ github.event.inputs.file_types_config }}'
              ;;
            *)
              echo "Unknown preset: ${{ github.event.inputs.config_preset }}"
              exit 1
              ;;
          esac
          
          echo "Selected configuration: ${{ github.event.inputs.config_preset }}"
          echo "CONFIG<<EOF" >> $GITHUB_OUTPUT
          echo "$CONFIG" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
      
      # Run the action against the test Java files
      - name: Run action on Java test files
        id: code-scan
        uses: ./
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          sourcePath: ${{ github.event.inputs.scan_path }}
          check-name: "Java Manual Quality Check"
          
          # Manual test settings
          scanChangedFilesOnly: false # Scan all files (no PR context)
          failOnQualityIssues: ${{ github.event.inputs.fail_on_issues }}
          enableScanCache: ${{ github.event.inputs.enable_cache }}
          outputFormats: ${{ github.event.inputs.output_formats }}
          
          # Configurable thresholds
          maxCriticalViolations: ${{ github.event.inputs.max_critical_violations }}
          maxMediumViolations: ${{ github.event.inputs.max_medium_violations }}
          
          # Use the configuration from the preset
          file-types-config: ${{ steps.set-config.outputs.CONFIG }}

      # Check if action is required based on violations
      # Using if: always() && condition to run even if previous step failed
      - name: Show results summary
        run: |
          echo "🎯 Configuration used: ${{ github.event.inputs.config_preset }}"
          echo "📁 Scan scope: All files in ${{ github.event.inputs.scan_path }}"
          echo "📊 Total violations: ${{ steps.code-scan.outputs.total-violations }}"
          echo "🚨 Critical violations: ${{ steps.code-scan.outputs.critical-violations }}"
          echo "⚠️ Medium violations: ${{ steps.code-scan.outputs.medium-violations }}"
          echo "❗ Action required: ${{ steps.code-scan.outputs.action-required }}"
