# Salesforce Code Quality Manual Test Workflow
#
# Purpose:
# This workflow allows manual testing of the action against Salesforce code files.
# It scans all files (not just changed ones) and is useful for:
# - Testing the action manually
# - Debugging issues
# - Demonstrating functionality
# - Running quality checks on any branch

name: Salesforce Code Quality Manual Test

on:
  workflow_dispatch:
    inputs:
      fail_on_issues:
        description: 'Fail workflow if quality issues are found'
        required: false
        default: 'false'
        type: boolean
      scan_path:
        description: 'Path to scan'
        required: false
        default: 'language-tests/salesforce/files/'
        type: string
      max_critical_violations:
        description: 'Maximum critical violations allowed'
        required: false
        default: '50'
        type: string
      max_medium_violations:
        description: 'Maximum medium violations allowed'
        required: false
        default: '100'
        type: string
      output_formats:
        description: 'Output formats (comma-separated: github,json,html,text)'
        required: false
        default: 'github'
        type: string
      enable_cache:
        description: 'Enable scan caching for faster runs'
        required: false
        default: 'true'
        type: boolean
      scan_all_files:
        description: 'Scan all files (true) or only changed files (false)'
        required: false
        default: 'true'
        type: boolean
      config_preset:
        description: 'Choose a predefined configuration'
        required: false
        default: 'salesforce-full'
        type: choice
        options:
          - 'salesforce-full'
          - 'salesforce-apex-only'
          - 'salesforce-lwc-only'
          - 'salesforce-aura-only'
          - 'salesforce-metadata-only'
          - 'custom'
      file_types_config:
        description: 'Custom file types configuration (JSON) - only used if config_preset is "custom"'
        required: false
        default: ''
        type: string

jobs:
  code-quality-manual-test:
    name: Manual Test on Salesforce Files
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      # Set the configuration based on the preset choice
      - name: Set configuration
        id: set-config
        run: |
          case "${{ github.event.inputs.config_preset }}" in
            "salesforce-full")
              CONFIG='[
                {
                  "name": "Classes",
                  "sourcePath": "language-tests/salesforce/files/classes/",
                  "fileExtensions": [".cls", ".cls-meta.xml"],
                  "analyzer": "pmd",
                  "rulesPaths": [
                    "./language-tests/salesforce/rulesets/pmd/apex/ruleset.xml"
                  ]
                },
                {
                  "name": "LWC",
                  "sourcePath": "language-tests/salesforce/files/lwc/",
                  "fileExtensions": [".js"],
                  "analyzer": "eslint",
                  "rulesPaths": [
                    "./language-tests/salesforce/rulesets/eslint/lwc/standard-ruleset.js"
                  ]
                },
                {
                  "name": "Aura",
                  "sourcePath": "language-tests/salesforce/files/aura/",
                  "fileExtensions": [".js"],
                  "analyzer": "eslint",
                  "rulesPaths": [
                    "./language-tests/salesforce/rulesets/eslint/aura/standard-ruleset.js"
                  ]
                },
                {
                  "name": "Fields",
                  "sourcePath": "language-tests/salesforce/files/objects/",
                  "fileExtensions": [".field-meta.xml"],
                  "analyzer": "pmd",
                  "rulesPaths": [
                    "./language-tests/salesforce/rulesets/pmd/xml/field-ruleset.xml"
                  ]
                }
              ]'
              ;;
            "salesforce-apex-only")
              CONFIG='[
                {
                  "name": "Classes",
                  "sourcePath": "language-tests/salesforce/files/classes/",
                  "fileExtensions": [".cls", ".cls-meta.xml"],
                  "analyzer": "pmd",
                  "rulesPaths": [
                    "./language-tests/salesforce/rulesets/pmd/apex/ruleset.xml"
                  ]
                }
              ]'
              ;;
            "salesforce-lwc-only")
              CONFIG='[
                {
                  "name": "LWC",
                  "sourcePath": "language-tests/salesforce/files/lwc/",
                  "fileExtensions": [".js"],
                  "analyzer": "eslint",
                  "rulesPaths": [
                    "./language-tests/salesforce/rulesets/eslint/lwc/standard-ruleset.js"
                  ]
                }
              ]'
              ;;
            "salesforce-aura-only")
              CONFIG='[
                {
                  "name": "Aura",
                  "sourcePath": "language-tests/salesforce/files/aura/",
                  "fileExtensions": [".js"],
                  "analyzer": "eslint",
                  "rulesPaths": [
                    "./language-tests/salesforce/rulesets/eslint/aura/standard-ruleset.js"
                  ]
                }
              ]'
              ;;
            "salesforce-metadata-only")
              CONFIG='[
                {
                  "name": "Fields",
                  "sourcePath": "language-tests/salesforce/files/objects/",
                  "fileExtensions": [".field-meta.xml"],
                  "analyzer": "pmd",
                  "rulesPaths": [
                    "./language-tests/salesforce/rulesets/pmd/xml/field-ruleset.xml"
                  ]
                }
              ]'
              ;;
            "custom")
              CONFIG='${{ github.event.inputs.file_types_config }}'
              ;;
            *)
              echo "Unknown preset: ${{ github.event.inputs.config_preset }}"
              exit 1
              ;;
          esac
          
          echo "Selected configuration: ${{ github.event.inputs.config_preset }}"
          echo "CONFIG<<EOF" >> $GITHUB_OUTPUT
          echo "$CONFIG" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
      
      # Run the action against Salesforce test files
      - name: Run action on Salesforce test files
        id: code-scan
        uses: ./
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          sourcePath: ${{ github.event.inputs.scan_path }}
          installSalesforcePlugins: true
          check-name: "Salesforce Manual Quality Check"
          
          # Manual test settings - use inputs or defaults
          scanChangedFilesOnly: ${{ github.event.inputs.scan_all_files == 'false' }}
          failOnQualityIssues: ${{ github.event.inputs.fail_on_issues }}
          enableScanCache: ${{ github.event.inputs.enable_cache }}
          outputFormats: ${{ github.event.inputs.output_formats }}
          
          # Configurable thresholds
          maxCriticalViolations: ${{ github.event.inputs.max_critical_violations }}
          maxMediumViolations: ${{ github.event.inputs.max_medium_violations }}
          
          # Use the configuration from the preset
          file-types-config: ${{ steps.set-config.outputs.CONFIG }}

      # Show results summary
      - name: Show results summary
        run: |
          echo "Configuration used: ${{ github.event.inputs.config_preset }}"
          echo "Total violations: ${{ steps.code-scan.outputs.total-violations }}"
          echo "Critical violations: ${{ steps.code-scan.outputs.critical-violations }}"
          echo "Medium violations: ${{ steps.code-scan.outputs.medium-violations }}"
          echo "Action required: ${{ steps.code-scan.outputs.action-required }}"
